import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_AU_NSW } from "next/font/google";
import "../../app/globals.css";
import { Toaster } from "sonner";
import { Navbar } from "../components/shared/Navbar";
import Footer from "../components/ui/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
});

const playwrite = Playwrite_AU_NSW({
    variable: "--font-playwrite"
});

export const metadata: Metadata = {
    title: "Wrap It",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${playwrite.variable}`}
        >
            <body>
                <Toaster />
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
