import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../../app/globals.css";
import { Toaster } from "sonner";
import SellerLayout from "@/app/components/admin/SellerLayout";
import { Navbar } from "@/app/components/admin/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Seller",
    description: "Generated by create next app"
};

export default function SellerPageLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Toaster />
                <div className="" >
                    <Navbar />
                    <SellerLayout>{children}</SellerLayout>
                </div>
            </body>
        </html>
    );
}
