import type { Metadata } from "next";
import "../../app/globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Giftly",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <Toaster />
                {children}
            </body>
        </html>
    );
}
