import type { Metadata } from "next";
import "../../app/globals.css";
import { Toaster } from "sonner";
import { Navbar } from "../components/shared/Navbar";
import { Playwrite_AU_NSW } from "next/font/google";

export const metadata: Metadata = {
    title: "Wrap It",
    description: "Generated by create next app"
};

const playwrite = Playwrite_AU_NSW({
    variable: "--font-playwrite"
});

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={`${playwrite.variable}`}>
            <body>
                <Navbar />
                <Toaster position="top-center" />
                {children}
            </body>
        </html>
    );
}
